{
  "version": 2,
  "build": {
    "commands": [
      "cd backend",
      "npm install"
    ]
  },
  "start": {
    "command": "cd backend && npm start"
  },
  "env": {
    "NODE_ENV": "production"
  }
}